export const courses = [
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL201', title: 'Applied Mathematics-III', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSP152', title: 'Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary  Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary  Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary  Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic  Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic  Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer  Programming  and Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer  Programming  and Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL251', title: 'Data Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL252', title: 'Operating Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL253', title: 'Object  Oriented  Programming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL254', title: 'Design and Analysis  of Algorithms', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL255', title: 'Computer Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL256', title: 'Software  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL257', title: 'Data  Communication', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL258', title: 'Computer  Organization  &  Architecture', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL259', title: 'Theory  of  Computation', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL351', title: 'Database  Management  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL352', title: 'Compiler Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL353', title: 'Data Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL354', title: 'Information  and  Network Security', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP354', title: 'Information  and  Network  Security  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL355', title: 'Artificial Intelligence', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP355', title: 'Artificial Intelligence  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'SCL254', title: 'Discrete  Mathematics', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL256', title: 'Digital Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP256', title: 'Digital Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL353', title: 'Microprocessor and  Interfacing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP353', title: 'Microprocessor and  Interfacing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSD351', title: 'Minor Project  -  01  CSD451  Major Project  -  02  B. Tech. (Computer Science and Engineering)  OVERALL CREDIT STRUCTURE                                                                                                                                                                 Departmental Elective (DE)  Course Code  Course  L-T-P  Credit  CSL356  Digital  Image  Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP356', title: 'Digital  Image  Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL357', title: 'Web Technologies', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL358', title: 'Information  Retrieval', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL359', title: 'Neuro-Fuzzy  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL451', title: 'Real Time Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL452', title: 'Cloud Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL454', title: 'Machine Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL453', title: 'Public  Key  Infrastructure  and  Trust Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP454', title: 'Machine  Learning  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL455', title: 'Parallel  and  Distributed  Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP455', title: 'Linux Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL457', title: 'Concepts  in  Blockchaining', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL458', title: 'Cyber Security and  Forensic', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL459', title: 'System  Programming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL460', title: 'Fundamental  Algorithms  in  Computational  Biology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL461', title: 'Wireless Sensor &  Ad Hoc networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL462', title: '5G Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL463', title: 'Geo Informatics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL464', title: 'Multimedia  Technology  and  Virtual Reality', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL458', title: 'Soft  Computing  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP467', title: 'Soft  Computing  Techniques Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL461', title: 'Robotics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP461', title: 'Robotics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL352', title: 'Digital  Signal  Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL355', title: 'Digital  Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL468', title: 'Embedded System  Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL525', title: 'Statistical  Models  for  Computer  Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL524', title: 'Optimization  Techniques  (Operation  Research)', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL527', title: 'Data Mining', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL529', title: 'Data Analytics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL531', title: 'Internet of Things  (IoT)', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL532', title: 'Advanced  Computer Network', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL534', title: 'Advanced  Cryptography', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL535', title: 'Edge Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP524', title: 'Programming in R', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer  Programming  and  Problem Solving  3-0-0    CSP151  Computer  Programming  and  Problem-Solving Lab  0-0-2    AIL251  Data Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP251', title: 'Data Structures Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL252', title: 'Operating Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP252', title: 'Operating Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL253', title: 'Object  Oriented  Programming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP253', title: 'Object  Oriented  Programming Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL254', title: 'Design and Analysis of  Algorithms', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP254', title: 'Design and Analysis of  Algorithms Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL255', title: 'Computer Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP255', title: 'Computer  Networks  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL256', title: 'Artificial Intelligence', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP256', title: 'Artificial  Intelligence  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL257', title: 'Machine Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP257', title: 'Machine Learning Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL258', title: 'Computer Organization  & Architecture', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'SCL254', title: 'Discrete Mathematics', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL256', title: 'Digital Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP256', title: 'Digital Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL351', title: 'Database Management  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP351', title: 'Database Management  Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL352', title: 'Advances in Machine  Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP352', title: 'Advances in Machine  Learning Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL353', title: 'Data Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP353', title: 'Data Science Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL354', title: 'Information  and  Network Security', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP354', title: 'Information  and  Network Security Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL355', title: 'Fundamentals of Data  Analytics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP355', title: 'Data Analytics using R', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL356', title: 'Introduction to Deep  Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL353', title: 'Microprocessor  and  Interfacing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP353', title: 'Microprocessor  and  Interfacing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AID351', title: 'Minor Project  -  01  AID451  Major Project  -  02              Humanities and Management (Core) (HM)  Course  Code  Course  L-T-P  Credit  HSP152  Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary  Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary  Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary  Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic  Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic  Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer  Programming  and Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer  Programming  and Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL357', title: 'Digital  Image  Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP357', title: 'Digital  Image  Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL358', title: 'Web Technologies', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL359', title: 'Information Retrieval', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL360', title: 'Neuro-Fuzzy  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL451', title: 'Real Time Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL361', title: 'Theory of Computation', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL362', title: 'Data Communication', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL363', title: 'Software Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP364', title: 'Software  Engineering  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL365', title: 'Compiler Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL451', title: 'Geo Informatics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL452', title: 'Cloud Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL453', title: 'Public  Key  Infrastructure and Trust  Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL454', title: 'Parallel and Distributed  Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIP454', title: 'Linux Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL455', title: 'Concepts  in  Block  Chaining', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL456', title: 'Cyber  Security  and  Forensic', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL457', title: 'System Programming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL458', title: 'Fundamental  Algorithms  in  Computational Biology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL459', title: 'Wireless Sensor & Ad  Hoc networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL460', title: '5G Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL461', title: 'Natural  Language  Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL462', title: 'Mobile Application', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'AIL463', title: 'Multimedia and Virtual  Reality', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL355', title: 'Digital Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL352', title: 'Digital  Signal  Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL458', title: 'Soft  Computing  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL525', title: 'Statistical Models for  Computer Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL524', title: 'Optimization  Techniques (Operation  Research)', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL527', title: 'Data Mining', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL531', title: 'Internet of Things (IoT)', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL532', title: 'Advanced  Computer  Network', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL534', title: 'Advanced Cryptography', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL535', title: 'Edge Computing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSP152', title: 'Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary  Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary  Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary  Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic  Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic  Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer  Programming  and Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer  Programming  and Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL251', title: 'Fluid Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL252', title: 'Engineering Geology', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL253', title: 'Building Materials and Construction Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL256', title: 'Surveying', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL257', title: 'Strength of Materials', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL281', title: 'Water Supply Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL282', title: 'Highway Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL357', title: 'Reinforced Concrete Structures', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL358', title: 'Steel Structures', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL359', title: 'Railway and Airport Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL360', title: 'Estimation and Costing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL381', title: 'Hydrology and Irrigation Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL382', title: 'Concrete Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL383', title: 'Soil Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL384', title: 'Wastewater Engineering and Pollution', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL385', title: 'Structural Analysis', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL386', title: 'Geotechnical Engineering', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP251', title: 'Fluid Mechanics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP252', title: 'Engineering Geology Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP256', title: 'Surveying Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP257', title: 'Strength of Materials Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP282', title: 'Highway Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP381', title: 'Hydrology and Irrigation Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP382', title: 'Materials Testing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP383', title: 'Soil Mechanics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP384', title: 'Environmental Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CED351', title: 'Minor Project  -  1  CED451  Major Project  -  2  B.Tech. (Civil Engineering)  Overall Credit Structure            Departmental Elective Courses Title  L-T-P  Credit  SCL453  Probability and Statistics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL451', title: 'Geomatics Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL452', title: 'Non-Destructive Testing of Materials', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL455', title: 'Rock Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL456', title: 'Industrial Waste Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL457', title: 'Environmental Impact and Risk Assessment', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL459', title: 'River Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL460', title: 'Traffic Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL461', title: 'Construction Planning and management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL464', title: 'Urban  Water  and  Environmental  Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL466', title: 'Advanced Highway Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL467', title: 'Groundwater Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL468', title: 'Hydraulic and Hydraulic Machines', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL471', title: 'Architectural  Planning  and  Design  of  Buildings', ltp: '2-2-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL481', title: 'Hydraulic Structures', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL482', title: 'Advanced Foundation Engineering', ltp: '3-1-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL483', title: 'Earth Retaining Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL484', title: 'Machine Learning and Data Analytics for  Civil Engineering Applications', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL485', title: 'Harbours and Tunneling', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL486', title: 'Earth and Rockfill Dams', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL487', title: 'Concepts of Green Building Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL488', title: 'Advanced Structural Analysis', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL502', title: 'Earthquake Resistance Design of Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL519', title: 'Geometric Design of Transportation Facilities', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL525', title: 'Traffic Engineering Design and Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL527', title: 'Ground Improvement Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL528', title: 'Advanced Soil Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL540', title: 'Environmental Geotechnology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL552', title: 'Advanced Concrete Structures', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL553', title: 'Prestressed Concrete Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL554', title: 'Bridge Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL555', title: 'Advanced Steel Structures', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL556', title: 'Geotechnical Earthquake Engineering', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL557', title: 'Water Storage Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL558', title: 'Structural Dynamics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP451', title: 'Geomatics Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP452', title: 'Non-Destructive Testing of Materials Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP455', title: 'Rock Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP484', title: 'Machine Learning and Data Analytics for Civil  Engineering Applications- Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP507', title: 'Geotechnical Design Studio', ltp: '1-0-4', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP508', title: 'RCC Structures Detailing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEP509', title: 'Structural Dynamics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic Electronics Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic Electronics Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic Electronics Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic Electronics Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL251', title: 'Signals and Systems', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL252', title: 'Analog Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP252', title: 'Analog Circuits  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL253', title: 'Analog Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP253', title: 'Analog Communication Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL254', title: 'Engineering Electromagnetics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL255', title: 'Solid State Devices', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL256', title: 'Digital Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP256', title: 'Digital Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL351', title: 'Linear Integrated Circuit', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP351', title: 'Linear Integrated Circuit Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL352', title: 'Digital Signal Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP352', title: 'Digital Signal Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL354', title: 'Antenna Theory', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL355', title: 'Digital Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP355', title: 'Digital Communication Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL356', title: 'Microwave Theory and Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP356', title: 'Microwave Theory and Techniques Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL359', title: 'Microprocessor and Interfacing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP359', title: 'Microprocessor and Interfacing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL360', title: 'Optical Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP360', title: 'Optical Communication Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL251', title: 'Basic Electrical Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP251', title: 'Basic Electrical Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL254', title: 'Control System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP254', title: 'Control System Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL251', title: 'Data Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP251', title: 'Data Structures Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL258', title: 'Computer  Organization  and  Architecture', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP361', title: 'Electronics Workshop and Tinkering  Lab', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL462', title: 'Electronic System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP462', title: 'Electronic System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL466', title: 'Finite Automata', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL467', title: 'Radio  Frequency and  Microwave  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL468', title: 'Embedded System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP468', title: 'Embedded System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL470', title: 'Wireless and Mobile Communications', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP470', title: 'Wireless and Mobile Communication  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL471', title: 'Radar and Satellite Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL473', title: 'FPGA based IC/System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP473', title: 'FPGA based IC/System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL474', title: 'Data Communication and Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL475', title: 'Information  Theory  &  Coding  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL476', title: 'Advanced Analog Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL477', title: 'Intelligent Instrumentation', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL519', title: 'VLSI/ULSI Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL531', title: 'Advanced Microwave Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL533', title: 'Advanced  Digital  Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL542', title: 'Image Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP542', title: 'Image Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL552', title: 'Advanced Machine Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP552', title: 'Advanced Machine Learning Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL563', title: 'Matrix Theory for System Analysis', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL564', title: 'Robotics Control and Computer Vision', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL565', title: 'Advanced Topics in Semiconductor  Devices', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL252', title: 'Operating System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP252', title: 'Operating System Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL353', title: 'Data Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP353', title: 'Data Science Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL255', title: 'Power Electronics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP255', title: 'Power Electronics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL201', title: 'Applied Mathematics-III', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSP152', title: 'Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer Programming and  Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer Programming and  Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL251', title: 'Basic Electrical Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP251', title: 'Basic Electrical Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL252', title: 'Measurement & Instrumentation', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP252', title: 'Measurement & Instrumentation Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL253', title: 'Electrical Machines I', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP253', title: 'Electrical Machines I  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL254', title: 'Control System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP254', title: 'Control System Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL255', title: 'Power Electronics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL256', title: 'Power System I', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL251', title: 'Signals and Systems', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL252', title: 'Analog Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP252', title: 'Analog Circuit Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL254', title: 'Engineering Electromagnetics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL256', title: 'Digital Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP256', title: 'Digital Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL351', title: 'Electrical Machines II', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP351', title: 'Electrical Machines II Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL352', title: 'Electric Drives', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP352', title: 'Electric Drives Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL353', title: 'Power System II', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL356', title: 'Advance Control System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP255', title: 'Power Electronics Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL355', title: 'Switchgear & Protection', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP355', title: 'Switchgear & Protection Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL351', title: 'Linear Integrated Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP351', title: 'Linear Integrated Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL359', title: 'Microprocessor and Interfacing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP359', title: 'Microprocessor and Interfacing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EED351', title: 'Minor Project  -  01  EED451  Major Project  -  02  B.Tech. Electrical & Electronics Engineering  OVERALL CREDIT STRUCTURE                        Departmental Elective (DE)  Course  Code  Course  L-T-P  Credit  EEP257  Electrical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP460', title: 'Control System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL352', title: 'Digital Signal Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP352', title: 'Digital Signal Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL473', title: 'FPGA based IC/System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP473', title: 'FPGA based IC/System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL401', title: 'Linear Algebra', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL402', title: 'Probability Theory and Statistics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL461', title: 'Robotics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP461', title: 'Robotics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL253', title: 'Object Oriented Programming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL251', title: 'Data Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP251', title: 'Data Structures Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL359', title: 'Neuro-Fuzzy Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSP152', title: 'Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer Programming and  Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer Programming and  Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL251', title: 'Mechanical  Behaviour  of  Materials', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL252', title: 'Engineering Thermodynamics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL253', title: 'Fluid Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP253', title: 'Fluid Mechanics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL254', title: 'Solid Mechanics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP254', title: 'Solid Mechanics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL255', title: 'Kinematics of Machines', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL256', title: 'Machine Drawing', ltp: '1-0-0', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP256', title: 'Machine Drawing Lab', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL257', title: 'Casting Welding and Forming', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP257', title: 'Casting Welding and Forming Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL258', title: 'Machining and Machine Tools', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP258', title: 'Machining and Machine Tools  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL351', title: 'Energy Conversion', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP351', title: 'Energy Conversion Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL352', title: 'Fluid Machines', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP352', title: 'Fluid Machines Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL353', title: 'Heat and Mass Transfer', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP353', title: 'Heat and Mass Transfer Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL354', title: 'Dynamics of Machines', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL355', title: 'Metrology and SQC', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP355', title: 'Metrology and SQC Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL356', title: 'Operations Management', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL357', title: 'Design of Machine Elements', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL451', title: 'Refrigeration & Air Conditioning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP451', title: 'Refrigeration & Air Conditioning  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL452', title: 'Mechanical Vibrations', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP452', title: 'Mechanical Vibrations Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MED351', title: 'Minor Project  -  01  MED451  Major Project  -  02  B.Tech. Mechanical Engineering  OVERALL CREDIT STRUCTURE                                                              Departmental Elective (DE)  Course  Code  Course  L-T-P  Credit  SCL453  Probability Theory and Statistics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL358', title: 'Measurement and Control', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP358', title: 'Measurement and Control Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL359', title: 'Fundamentals of Electric Vehicles', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL360', title: 'Introduction to Data Science for  Mechanical Engineers', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL453', title: 'Operation Research', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL454', title: 'Industrial Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL455', title: 'Compressible and Incompressible  Fluid Flow', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL456', title: 'Computer Aided Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP456', title: 'Computer Aided Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL457', title: 'Computer Integrated  Manufacturing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL458', title: 'Mechatronics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP458', title: 'Mechatronics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL459', title: 'Gas Turbine and Compressor', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL460', title: 'Quality Assurance', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL461', title: 'Robotics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP461', title: 'Robotics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL462', title: 'Automation in Production', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL463', title: 'Power Plant Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL464', title: 'Renewable Energy Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL465', title: 'Automobile Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP465', title: 'Automobile Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL466', title: 'I. C. Engines and Hybrid Vehicles', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP466', title: 'I. C. Engines and Hybrid Vehicles  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL467', title: 'Processing of Non-Metals', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL468', title: 'Additive Manufacturing  Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP468', title: 'Additive Manufacturing  Technology Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL469', title: 'Material Resource Planning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP471', title: 'Machine System Design Lab', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL102', title: 'Applied Mathematics-I', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MAL103', title: 'Applied Mathematics-II', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHL151', title: 'Applied Physics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'PHP151', title: 'Applied Physics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYL101', title: 'Applied Chemistry', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CYP101', title: 'Applied Chemistry Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSP152', title: 'Technical Communication', ltp: '1-2-2', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'HSL151', title: 'Social Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL152', title: 'Elementary  Mechanical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL151', title: 'Elementary  Electrical  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP151', title: 'Elementary  Electrical  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL151', title: 'Basic  Electronics  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP151', title: 'Basic  Electronics  Engineering Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEL151', title: 'Engineering Drawing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP151', title: 'Engineering Drawing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL151', title: 'Computer  Programming  and Problem Solving', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP151', title: 'Computer  Programming  and Problem Solving Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'MEP152', title: 'Mechanical Workshop', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CEL151', title: 'Environmental Science', ltp: '2-0-0', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL251', title: 'Signals and Systems', ltp: '3-2-0', credits: 4, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL252', title: 'Analog Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP252', title: 'Analog Circuits  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL253', title: 'Analog Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP253', title: 'Analog Communication Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL254', title: 'Engineering Electromagnetics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL255', title: 'Solid State Devices', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL256', title: 'Digital Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP256', title: 'Digital Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL351', title: 'Linear Integrated Circuit', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP351', title: 'Linear Integrated Circuit Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL352', title: 'Digital Signal Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP352', title: 'Digital Signal Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL354', title: 'Antenna Theory', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL355', title: 'Digital Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP355', title: 'Digital Communication Systems Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL356', title: 'Microwave Theory and Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP356', title: 'Microwave Theory and Techniques Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL359', title: 'Microprocessor and Interfacing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP359', title: 'Microprocessor and Interfacing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL360', title: 'Optical Communication Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP360', title: 'Optical Communication Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL251', title: 'Basic Electrical Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP251', title: 'Basic Electrical Circuits Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL254', title: 'Control System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP254', title: 'Control System Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL251', title: 'Data Structures', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP251', title: 'Data Structures Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL258', title: 'Computer Organization and  Architecture', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECD351', title: 'Minor Project  -  01  ECD451  Major Project  -  02  B.Tech (Electronics and Communication  Engineering)  OVERALL CREDIT STRUCTURE                                                                                                                               Department Elective (DE)  L-T-P  Credit  ECP361  Electronics Workshop and Tinkering  Lab', ltp: '0-0-4', credits: 2, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL462', title: 'Electronic System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP462', title: 'Electronic System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL466', title: 'Finite Automata', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL467', title: 'Radio Frequency and Microwave  Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL468', title: 'Embedded System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP468', title: 'Embedded System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL470', title: 'Wireless and Mobile Communications', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP470', title: 'Wireless and Mobile Communication  Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL471', title: 'Radar and Satellite Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL473', title: 'FPGA based IC/System Design', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP473', title: 'FPGA based IC/System Design Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL474', title: 'Data Communication and Networks', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL475', title: 'Information Theory & Coding  Techniques', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL476', title: 'Advanced Analog Circuits', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL477', title: 'Intelligent Instrumentation', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL519', title: 'VLSI/ULSI Technology', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL531', title: 'Advanced Microwave Engineering', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL533', title: 'Advanced Digital Communication  Systems', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL542', title: 'Image Processing', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP542', title: 'Image Processing Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL552', title: 'Advanced Machine Learning', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECP552', title: 'Advanced Machine Learning Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL563', title: 'Matrix Theory for System Analysis', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL564', title: 'Robotics Control and Computer Vision', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'ECL565', title: 'Advanced Topics in Semiconductor  Devices', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL252', title: 'Operating System', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP252', title: 'Operating System Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSL353', title: 'Data Science', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'CSP353', title: 'Data Science Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEL255', title: 'Power Electronics', ltp: '3-0-0', credits: 3, type: 'UNKNOWN', department: 'CSE' },
  { code: 'EEP255', title: 'Power Electronics Lab', ltp: '0-0-2', credits: 1, type: 'UNKNOWN', department: 'CSE' },
];
